version: 2
updates:0
- package-ecosystem: pip
  directory: "/"
  schedule:every day
    interval: daily
  open-pull-requests-limit: 10
  groups:idk
    docusaurus:idk
      patterns:idk
      - "@docusaurus/*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:evrey day
    interval: weekly
  open-pull-requests-limit: 10
